version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g yarn
      - yarn install

  pre_build:
    commands:
      - echo Running tests...
      - yarn test:ci
      - echo Setting environment variable SERVER_URL from CodeBuild parameters...
      - export REACT_APP_SERVER=$SERVER_URL
      - echo REACT_APP_SERVER is set to $SERVER_URL

  build:
    commands:
      - echo Build started on `date`
      - yarn build
      - echo Build completed on `date`

  post_build:
    commands:
      # S3에 static 폴더 업로드
      - echo Uploading static files to S3...
      - aws s3 sync build/static/ s3://${STATIC_BUCKET}/static/ --delete --cache-control "max-age=31536000,public,immutable"

      # static 폴더 삭제 (EC2에 배포 안 함)
      - echo Removing static folder from build...
      - rm -rf build/static

      # CodeDeploy용 파일 복사
      - echo Copying deployment files...
      - cp appspec.yml build/
      - cp -r scripts build/

artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - 'node_modules/**/*'
